language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U -r requirements.txt
  - "sudo apt-get install graphviz"
# command to run tests
script:
   -pytest -vvv tests
  
