language: python
python:
  - "3.6"
# command to install dependencies
addons:
  apt:
    packages:
      - graphviz
install:
  - pip install -U -r requirements.txt
  - pip install .
# command to run tests
script:
   - pytest -vvv tests
  
